apiVersion: v1
kind: Service
metadata:
  name: msdemo
spec:
  type: NodePort
  selector:
    app: demo
    department: configuration
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080